yatube/posts/urls.py
from django.urls import path
from . import views


app_name = 'posts'

urlpatterns = [
    # Главная страница
    path('', views.index, name='index'),
    path('group/<slug>/', views.group_posts, name='group_list')
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField()
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.CASCADE,
        blank=True,
        null=True)

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Group


def index(request):
    # Одна строка вместо тысячи слов на SQL:
    # в переменную posts будет сохранена выборка из 10 объектов модели Post,
    # отсортированных по полю pub_date по убыванию (от больших значений к меньшим)
    posts = Post.objects.order_by('-pub_date')[:10]
    # В словаре context отправляем информацию в шаблон
    context = {
        'posts': posts,
    }
    return render(request, 'posts/index.html', context)

def group_posts(request, slug):
    # Функция get_object_or_404 получает по заданным критериям объект
    # из базы данных или возвращает сообщение об ошибке, если объект не найден.
    # В нашем случае в переменную group будут переданы объекты модели Group,
    # поле slug у которых соответствует значению slug в запросе
    group = get_object_or_404(Group, slug=slug)

    # Метод .filter позволяет ограничить поиск по критериям.
    # Это аналог добавления
    # условия WHERE group_id = {group_id}
    posts = Post.objects.filter(group=group).order_by('-pub_date')[:10]
    context = {
        'group': group,
        'posts': posts,
    }
    return render(request, 'posts/group_list.html', context)

yatube/templates/base.html
<!DOCTYPE html> <!-- Используется html 5 версии -->
<html lang="ru"> <!-- Язык сайта - русский -->
  <head>
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    {% load static %}
    <link rel="icon" href="img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    <header>
      {% include 'includes/header.html' %}
    </header>
    <main>
      {% block content %}
      {% endblock %}
    </main>
    <!-- Использованы классы бустрапа: -->
    <!-- border-top: создаёт тонкую линию сверху блока -->
    <!-- text-center: выравнивает текстовые блоки внутри блока по центру -->
    <!-- py-3: контент внутри размещается с отсупом сверху и снизу -->
    <footer>
      {% include 'includes/footer.html' %}
    </footer>
  </body>
</html>

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
  <p>© 2020 Copyright <span style="color:red">Ya</span>tube</p>
</footer>

yatube/templates/includes/header.html
<header>
  <!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
  <!-- В дальнейшем тут будет создано полноценное меню -->
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
       <!-- ссылка должна вести на главную страницу -->
      <a class="navbar-brand" href="">
        <img src="static/img/logo.png" width="30" height="30" class="d-inline-block align-top" alt="">
        <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
        <span style="color:red">Ya</span>tube
      </a>
    </div>
  </nav>
</header>

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}Записи сообщества{% endblock %}
{% block content %}
  <div class="container" href="{% url 'posts:group_list' group %}">
    <h1>Записи сообщества: {{ group.title }}</h1>
        <p>
          {{ group.description }}
        </p>
        {% for post in posts %}
          <ul>
            <li>
              Автор: {{ post.author.get_full_name }}
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>
          <p>{{ post.text }}</p>
          {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
  </div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}Последние обновления на сайте{% endblock %}

{% block content %}
    <h1>Последние обновления на сайте</h1>
    <div class="container">
        {% for post in posts %}
          <ul>
            <li>
              Автор: {{ post.author.get_full_name }}
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>
          <p>{{ post.text }}</p>
          {% if post.group %}
            <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
          {% endif %}
          {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
    </div>
{% endblock %}